name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install flask pytest pytest-playwright playwright
      - run: playwright install --with-deps chromium
      - run: pytest -v
